name: gh-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with full history (fetch-depth: 0)
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # Setup Python 3.x environment
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      # Install all the necessary dependencies in one step
      - name: Install dependencies
        run: |
          pip install mkdocs>=1.2.3
          pip install mkdocs-material
          pip install mkdocs-click
          pip install pymdown-extensions
          pip install mkdocs-rss-plugin
      
      # Deploy the site using mkdocs
      - name: Deploy with MkDocs
        run: mkdocs gh-deploy --force
